### ISSUE TITLE
Piston Extension

### ISSUE THREAD

**Issue by MrSwalbert** [royalcraft-co/bug-reports#10]
**Description of the Bug**
Sometimes when pistons extend, they do not retract as intended. This bug doesn't always occur.

**Steps to Reproduce**
1. Place a piston.
2. Power it with a redstone torch.
3. Remove the restone torch.
4. The piston may not retract properly.

**Expected Behavior**
The piston should retract properly.

**Screenshots**
https://youtu.be/5mzT8iK9DhU

**Client-Side Information**
OS: Windows 10
MC Version: 1.8.9 (sometimes 1.9.4)
Client: Forge and Liteloader

**Additional Information**
This doesn't seem to happen for me on 1.12.2. Maybe there is a plugin we can install to fix this?

**Comment by gusuu1** [comment]
This looks just like a visual glitch to me. When the player jumped on the piston they got teleported down to the ground. Reopen if it turns out otherwise.
