### ISSUE TITLE
Disappearing Cake

### ISSUE THREAD

**Issue by TheEncryption** [royalcraft-co/bug-reports#11]
**Description of the Bug**
If you attempt to buy more than one cake at a time in skyblock using /shop it will take your money, give you the amount you bought and then immediately the cake disappears, you can buy one at a time but that's it (I like to buy in bulk >_>)

**Steps to Reproduce**
1. Go to /shop
2. Click on Food, then Cake
3. Select any amount more than four
4. Purchase that amount

**Expected Behavior**
I expected to be able to buy more than one cake at a time but instead I was met with disappointment.

**Screenshots**
Here's a video instead: https://youtu.be/a5ZpFWNK4-E

**Client-Side Information**
OS: Windows
MC Version: 1.8
Client: Minecraft Launcher

**Additional Information**
Add any other information about the problem here.

**Comment by MrSwalbert** [comment]
The item stack plugin was detecting it as an illegal stack. I've added cake to the whitelist so that you can satisfy your needs!
