### ISSUE TITLE
skyblock ranks on factions

### ISSUE THREAD

**Issue by loveunderscorebox** [royalcraft-co/bug-reports#12]
**Description of the Bug**
skyblock ranks carry over to factions

**Steps to Reproduce**
have a rank on skyblock
go on factions

**Expected Behavior**
that not to happen

**Screenshots**
![2020-05-23_22 45 05](https://user-images.githubusercontent.com/65555949/82741171-5c008c00-9d47-11ea-8bbf-7377eaaefbcc.png)

? not sure if that worked
**Client-Side Information**
Any

**Additional Information**
Nope

**Comment by MrSwalbert** [comment]
Should hopefully be fixed next restart. If not, reopen this issue.

**Comment by loveunderscorebox** [comment]
its still happening
![2020-05-24_19 46 39](https://user-images.githubusercontent.com/65555949/82762155-56fb1580-9df7-11ea-9522-6b2e12e73bc1.png)
 in chat

**Comment by MrSwalbert** [comment]
Was just an issue for him. I've fixed his ranks.
