### ISSUE TITLE
kit once un redeemable

### ISSUE THREAD

**Issue by loveunderscorebox** [royalcraft-co/bug-reports#14]
**Description of the Bug**
when you try to claim a kit once on space, it says that you need to wait a lot of years to do so.

**Steps to Reproduce**
1. have never claimed it before
2. go to space
3. do /kits
4. click basic kits
5. hover over kit once
6. see the problem

**Expected Behavior**
it lets me redeem it

**Client-Side Information**
Any
**Additional Information**
none

**Comment by loveunderscorebox** [comment]
I should add that maybe instead of making the cool down for claiming it like 300k years or whatever, just make it become locked for you.

**Comment by gusuu1** [comment]
Thanks for reporting this issue, it should now be fixed.
