### ISSUE TITLE
Nametags

### ISSUE THREAD

**Issue by ColdSight** [royalcraft-co/bug-reports#15]
**Description of the Bug**
Walk towards a player and all it shows is there name, no faction, no rank, nothing.

**Steps to Reproduce**
1. Go up to any player and no faction, rank, or anything else and it doesn't show up

**Expected Behavior**
You should be able to see faction name, and rank.

**Screenshots**
https://gyazo.com/c7952216dcd5231fb89c3ed2e3d8d8f1

**Client-Side Information**
Any

**Additional Information**
Nothing else.

**Comment by MrSwalbert** [comment]
Should be added next restart. If not, reopen your other issue and state this there.
