### ISSUE TITLE
Getpos not having a 3 day cooldown.

### ISSUE THREAD

**Issue by ColdSight** [royalcraft-co/bug-reports#16]
**Description of the Bug**
Getpos was supposed to be once every 3 days but it is now instant.

**Steps to Reproduce**
1. Type '/getpos'
2. One second later you can do '/getpos'

**Expected Behavior**
Once every 3 days.

**Screenshots**
https://gyazo.com/4d555cabec58873a752c6f1b14e0eeeb

**Client-Side Information**
Any player can do this command infinitely. 

**Additional Information**
No.

**Comment by gusuu1** [comment]
I'm not sure where this "cooldown" has been set, waiting for a response.

**Comment by gusuu1** [comment]
Just got told this issue has been sorted already, closed.
