### ISSUE TITLE
Console Kick Bug Report

### ISSUE THREAD

**Issue by ColdSight** [royalcraft-co/bug-reports#2]
Describe the bug: When the console detects someone using too many packets it kicks them and shows it in chat about 30x.

To Reproduce Steps to reproduce the behavior: I am not sure how to replicate it but I believe whenever you send tons of packets to the server the console detects that and kicks that person 30x.

Screenshots If applicable: https://gyazo.com/e6e69c14f77d10cf5d94fc336c543fa2

Describe the bug A clear and concise description of what the bug is: Kicks a player that is sending tons of packets to the server and gets kicked 30 times and shows up in chat and floods chat.

Desktop (please complete the following information): N/A

Additional context Add any other context about the problem here: N/A

**Comment by gusuu1** [comment]
I'll be looking into this

**Comment by MrSwalbert** [comment]
:beg: :beg: :beg: :beg:
Please can you make it **/ekick** or just disconnect the player instead of using LiteBans so it doesn't show on a player's punishment history?

**Comment by gusuu1** [comment]
> :beg: :beg: :beg: :beg:
> Please can you make it **/ekick** or just disconnect the player instead of using LiteBans so it doesn't show on a player's punishment history?

Changed the command to /ekick, assuming staff without * perm don't have permission to see Essentials kick messages this should be solved.

**Comment by gusuu1** [comment]
**Update:** changed it to npc kick, which doesn't display anything.
