### ISSUE TITLE
To Do: Staff Panel

### ISSUE THREAD

**Issue by gusuu1** [royalcraft-co/bug-reports#3]
- [ ] LiteBansUtils: -S ➡️ -s
- [ ] Add -s for /bot

**Comment by MrSwalbert** [comment]
- [x] **Only ban and mute punishments should be counted when using** `/evader`.
**Change:** it.staffpanel.sql > LiteBansUtils.java
_From:_
`public static void extendPunishments(String staff, UUID punished, String evader){`
`    banEvader(punished, evader, "bans");`
`    banEvader(punished, evader, "mutes");`
`    banEvader(punished, evader, "warnings");`
`    banEvader(punished, evader, "kicks");`
`    extend(staff, punished, "warnings");`
`    extend(staff, punished, "bans");`
`    extend(staff, punished, "kicks");`
`    extend(staff, punished, "mutes");`
`}`
_To:_
`public static void extendPunishments(String staff, UUID punished, String evader){`
`    banEvader(punished, evader, "bans");`
`    banEvader(punished, evader, "mutes");`
`    extend(staff, punished, "bans");`
`    extend(staff, punished, "mutes");`
`}`

- [x] **Make** `/evader` **punishments (the ones where the evading account become banned) silent, not completely suppressed.**
**Change:** it.staffpanel.sql > LiteBansUtils,java
_From:_
`String command = (type.contains("ings") ? type.replace("ings", "") : type.replace("s", "")) + " -S "
                                + evader + " " + (rs.getString("reason").endsWith(main.getConfig().getString("evader.extended-flag"))?rs.getString("reason").replace(main.getConfig().getString("evader.extended-flag"), ""):rs.getString("reason")) + " " + main.getConfig().getString("evader.evasion-flag").replace("%player%", Bukkit.getOfflinePlayer(punished).getName())
                                + " --sender=" + rs.getString("banned_by_name") + " --sender-uuid=" + rs.getString("banned_by_uuid");`
_To:_
`String command = (type.contains("ings") ? type.replace("ings", "") : type.replace("s", "")) + " -s "
                                + evader + " " + (rs.getString("reason").endsWith(main.getConfig().getString("evader.extended-flag"))?rs.getString("reason").replace(main.getConfig().getString("evader.extended-flag"), ""):rs.getString("reason")) + " " + main.getConfig().getString("evader.evasion-flag").replace("%player%", Bukkit.getOfflinePlayer(punished).getName())
                                + " --sender=" + rs.getString("banned_by_name") + " --sender-uuid=" + rs.getString("banned_by_uuid");`

- [x] **Make** `/bot` **punishments silent.**
**Change:** it.staffpanel.commands > Bot.java
_From:_
`Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "ipban "+args[0]+" --sender="+sender.getName()+" "+Utils.replaceColors(main.getConfig().getString("bot-reason")));`
_To:_
`Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "ipban -s "+args[0]+" --sender="+sender.getName()+" --sender-uuid="+sender.getUUID()+" "+Utils.replaceColors(main.getConfig().getString("bot-reason")));`

**Comment by gusuu1** [comment]
Updated.
