### ISSUE TITLE
Spawner Logging

### ISSUE THREAD

**Issue by MrSwalbert** [royalcraft-co/bug-reports#4]
**Describe the bug**
The mining and placing of spawners is not logged with CoreProtect or `/f inspect` (even with your plugin Gusuu) - please have spawner placement and mining logged in both.

**To Reproduce**
N/A

**Comment by gusuu1** [comment]
Is this also not working when using the `/co lookup r:<radius> t:<time> a:interact` command?

**Comment by MrSwalbert** [comment]
Doesn’t work.

**Comment by gusuu1** [comment]
> Doesn’t work. 

Is the plugin enabled? (/pl or /plugman list)

**Comment by MrSwalbert** [comment]
Yeah: https://gyazo.com/677abac0264a4c80b94b3c03b9d98cc7

**Comment by gusuu1** [comment]
This will change on the "revamp".
