### ISSUE TITLE
[BUG] Hub - Losing Items in Hub

### ISSUE THREAD

**Issue by SapQls** [royalcraft-co/bug-reports#5]
**Describe the bug**
In the hub, if you die (From ex. Parkour) you lose all your items as well as your effects.

**To Reproduce**
1. Go to hub
2. Jump down and die
3. You lose all your stuff

**Expected behavior**
You lose all your items & effects

**Screenshots**
Not needed

**Desktop (please complete the following information):**
Any version / client

**Additional context**

**Comment by gusuu1** [comment]
When rejoining the lobby it gives your stuff back right?

**Comment by MrSwalbert** [comment]
No you don't. The hub selector doesn't work either. Pretty Revvs is working on a new hub?

**Comment by gusuu1** [comment]
Indeed, won't fix for now.
