### ISSUE TITLE
[BUG] IS Value Dropping

### ISSUE THREAD

**Issue by SapQls** [royalcraft-co/bug-reports#7]
**Describe the bug**
Some players IS Value is going down for some reason. (#ticket-2724)

**To Reproduce**
Not sure how or why it happens.

**Expected behavior**
First your IS level maybe is 1.5M
The next day it maybe is 1.1M but you haven't removed anything.

**Screenshots**
Screenshots in ticket #ticket-2724

**Desktop (please complete the following information):**
Not sure.

**Additional context**
Nothing additional.

**Comment by gusuu1** [comment]
This is a known issue, it has to do with their miner minions calculating the levels too quickly, they are basically "ghost" levels.
